"""
Demo: run ViTForIQA on real labeled samples from a dataset JSON and display
predicted vs. ground-truth quality distributions.

Images and labels come from the dataset (e.g. KADID10K) — labels are real
human MOS-derived soft labels, not generated by this script.

Usage:
    python3 demo.py [--model-path PATH] \
                    [--head-path PATH] \
                    [--dataset-json ../data/Data-DeQA-Score/KADID10K/metas/train_kadid_8k.json] \
                    [--data-root   ../data/Data-DeQA-Score] \
                    [--num-samples 4] \
                    [--seed 0] \
                    [--out demo.png]
"""

import argparse
import json
import os
import random
import sys
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import torch
from PIL import Image
from transformers.models.clip.image_processing_clip import CLIPImageProcessor

sys.path.insert(0, ".")
from src.constants import (
    DEMO_ARG_SPECS,
    DEMO_GT_COLOR,
    DEMO_LEVELS,
    DEMO_PRED_COLOR,
)
from src.utils import expand2square
from src.model import ViTForIQA

LEVELS = DEMO_LEVELS
PRED_COLOR = DEMO_PRED_COLOR
GT_COLOR = DEMO_GT_COLOR


# ------------------------------------------------------------------ #
# Dataset loading                                                      #
# ------------------------------------------------------------------ #

def load_dataset_samples(json_path, data_root, num_samples, seed, allowed_indices=None):
    """Load random labeled samples that have real level_probs from the JSON."""
    with open(json_path) as f:
        data = json.load(f)
    data = [s for s in data if s.get("level_probs") is not None]
    if not data:
        raise ValueError(f"No samples with level_probs found in {json_path}")
    if allowed_indices is not None:
        data = [data[i] for i in allowed_indices if i < len(data)]
    rng = random.Random(seed)
    chosen = rng.sample(data, min(num_samples, len(data)))

    results = []
    for s in chosen:
        img_path = os.path.join(data_root, s["image"])
        img = Image.open(img_path).convert("RGB")
        title = os.path.basename(s["image"])
        results.append({
            "title":       title,
            "image":       img,
            "gt_score":    s["gt_score_norm"],   # normalized MOS (1–5)
            "gt_probs":    s["level_probs"],      # real soft label from human ratings
        })
    return results


# ------------------------------------------------------------------ #
# Model                                                                #
# ------------------------------------------------------------------ #

def get_device():
    if torch.cuda.is_available():
        return torch.device("cuda:0")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def load_model(model_path, head_path, device):
    model = ViTForIQA.from_pretrained(model_path, torch_dtype=None, softkl_loss=True)
    if head_path:
        head_sd = torch.load(head_path, map_location="cpu")
        missing, unexpected = model.load_state_dict(head_sd, strict=False)
        if unexpected:
            print(f"[demo] Unexpected head keys: {unexpected}")
        print(f"[demo] Head weights loaded from explicit path {head_path}")
    print(f"[demo] Resolved checkpoint: {getattr(model, 'resolved_checkpoint_path', model_path)}")
    model = model.to(device=device, dtype=torch.float32)
    model.eval()
    return model


@torch.inference_mode()
def score_images(model, processor, pil_images, device):
    tensors = []
    for img in pil_images:
        img = expand2square(img, tuple(int(x * 255) for x in processor.image_mean))
        t = processor.preprocess(img, return_tensors="pt")["pixel_values"][0]
        tensors.append(t)
    batch = torch.stack(tensors).to(device=device, dtype=torch.float32)
    output = model(images=batch)
    probs  = torch.softmax(output.logits, dim=-1).cpu().numpy()   # (N, 5)
    scores = (probs * np.array([5, 4, 3, 2, 1])).sum(axis=-1)    # (N,)
    return probs, scores


# ------------------------------------------------------------------ #
# Plot                                                                 #
# ------------------------------------------------------------------ #

def make_plot(samples, pred_probs, pred_scores, out_path):
    n = len(samples)
    x = np.arange(len(LEVELS))

    fig = plt.figure(figsize=(4.8 * n, 7.2))
    gs  = gridspec.GridSpec(2, n, height_ratios=[1, 1.5], hspace=0.38, wspace=0.38)

    for i, s in enumerate(samples):
        gt_probs  = np.array(s["gt_probs"])
        gt_score  = float(s["gt_score"])

        # ---- thumbnail ----
        ax_img = fig.add_subplot(gs[0, i])
        ax_img.imshow(s["image"])
        ax_img.axis("off")
        ax_img.set_title(s["title"], fontsize=9, pad=4)

        # ---- overlapping distributions ----
        ax_dist = fig.add_subplot(gs[1, i])
        ax_dist.fill_between(x, pred_probs[i], color=PRED_COLOR, alpha=0.24)
        ax_dist.plot(
            x, pred_probs[i], color=PRED_COLOR, marker="o", linewidth=2.0,
            label=f"Pred ({pred_scores[i]:.2f})",
        )
        ax_dist.fill_between(x, gt_probs, color=GT_COLOR, alpha=0.24)
        ax_dist.plot(
            x, gt_probs, color=GT_COLOR, marker="o", linewidth=2.0,
            label=f"GT ({gt_score:.2f})",
        )

        ax_dist.set_xticks(x)
        ax_dist.set_xticklabels(LEVELS, fontsize=8)
        ax_dist.set_xlim(x[0], x[-1])
        ax_dist.set_ylim(0, 1)
        ax_dist.set_ylabel("Probability", fontsize=9)
        ax_dist.grid(axis="y", alpha=0.25, linewidth=0.8)
        ax_dist.tick_params(axis="y", labelsize=8)
        ax_dist.legend(fontsize=7.5, loc="upper right")
        ax_dist.set_title("Overlapping Label Distributions", fontsize=9, pad=4)

        for probs, color, y_offset in (
            (pred_probs[i], PRED_COLOR, 0.018),
            (gt_probs, GT_COLOR, -0.035),
        ):
            for xi, p in zip(x, probs):
                if p > 0.05:
                    ax_dist.text(
                        xi, min(max(p + y_offset, 0.015), 0.985),
                        f"{p:.2f}", ha="center", va="bottom",
                        fontsize=6.5, color=color,
                    )

    fig.suptitle("ViTForIQA — Predicted vs. Real Ground-Truth Label", fontsize=13, y=1.01)
    fig.savefig(out_path, bbox_inches="tight", dpi=150)
    print(f"Saved demo plot to {out_path}")


# ------------------------------------------------------------------ #
# Main                                                                 #
# ------------------------------------------------------------------ #

def main(args):
    device = get_device()
    print(f"Device: {device}")

    repo_root = Path(__file__).resolve().parent
    args.dataset_json = str((repo_root / args.dataset_json).resolve())
    args.data_root = str((repo_root / args.data_root).resolve())

    processor = CLIPImageProcessor.from_pretrained(args.preprocessor_path)
    model     = load_model(args.model_path, args.head_path, device)

    samples = load_dataset_samples(
        json_path       = args.dataset_json,
        data_root       = args.data_root,
        num_samples     = args.num_samples,
        seed            = args.seed,
        allowed_indices = getattr(args, "allowed_indices", None),
    )

    pil_images  = [s["image"] for s in samples]
    pred_probs, pred_scores = score_images(model, processor, pil_images, device)

    for s, score, probs in zip(samples, pred_scores, pred_probs):
        dist = "  ".join(f"{l}={p:.2f}" for l, p in zip(LEVELS, probs))
        print(f"{s['title']:<30}  pred={score:.2f}  gt={s['gt_score']:.2f}  [{dist}]")

    make_plot(samples, pred_probs, pred_scores, args.out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    for arg_spec in DEMO_ARG_SPECS:
        parser.add_argument(*arg_spec["flags"], **arg_spec["kwargs"])
    args = parser.parse_args()
    main(args)
