"""
Demo: run ViTForIQA on real labeled samples from a dataset JSON and display
predicted vs. ground-truth quality distributions.

Images and labels come from the dataset (e.g. KADID10K) — labels are real
human MOS-derived soft labels, not generated by this script.

Usage:
    python3 demo.py [--model-path checkpoints/DeQA-Score-Mix3] \
                    [--head-path  checkpoints/DeQA-Score-Mix3/head.bin] \
                    [--dataset-json ../data/Data-DeQA-Score/KADID10K/metas/train_kadid_8k_new.json] \
                    [--data-root   ../data/Data-DeQA-Score] \
                    [--num-samples 4] \
                    [--seed 0] \
                    [--out demo.png]
"""

import argparse
import json
import os
import random
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import torch
from PIL import Image
from transformers.models.clip.image_processing_clip import CLIPImageProcessor

sys.path.insert(0, ".")
from src.mm_utils import expand2square
from src.model import ViTForIQA

LEVELS = ["excellent", "good", "fair", "poor", "bad"]
PRED_COLOR = "#3498db"
GT_COLOR   = "#e67e22"


# ------------------------------------------------------------------ #
# Dataset loading                                                      #
# ------------------------------------------------------------------ #

def load_dataset_samples(json_path, data_root, num_samples, seed):
    """Load random labeled samples that have real level_probs from the JSON."""
    with open(json_path) as f:
        data = json.load(f)
    data = [s for s in data if s.get("level_probs") is not None]
    if not data:
        raise ValueError(f"No samples with level_probs found in {json_path}")
    rng = random.Random(seed)
    chosen = rng.sample(data, min(num_samples, len(data)))

    results = []
    for s in chosen:
        img_path = os.path.join(data_root, s["image"])
        img = Image.open(img_path).convert("RGB")
        title = os.path.basename(s["image"])
        results.append({
            "title":       title,
            "image":       img,
            "gt_score":    s["gt_score_norm"],   # normalized MOS (1–5)
            "gt_probs":    s["level_probs"],      # real soft label from human ratings
        })
    return results


# ------------------------------------------------------------------ #
# Model                                                                #
# ------------------------------------------------------------------ #

def get_device():
    if torch.cuda.is_available():
        return torch.device("cuda:0")
    if torch.backends.mps.is_available():
        return torch.device("mps")
    return torch.device("cpu")


def load_model(model_path, head_path, device):
    model = ViTForIQA.from_pretrained(model_path, torch_dtype=None)
    if head_path:
        head_sd = torch.load(head_path, map_location="cpu")
        missing, unexpected = model.load_state_dict(head_sd, strict=False)
        if unexpected:
            print(f"[demo] Unexpected head keys: {unexpected}")
    model = model.to(device=device, dtype=torch.float32)
    model.eval()
    return model


@torch.inference_mode()
def score_images(model, processor, pil_images, device):
    tensors = []
    for img in pil_images:
        img = expand2square(img, tuple(int(x * 255) for x in processor.image_mean))
        t = processor.preprocess(img, return_tensors="pt")["pixel_values"][0]
        tensors.append(t)
    batch = torch.stack(tensors).to(device=device, dtype=torch.float32)
    output = model(images=batch)
    probs  = torch.softmax(output.logits, dim=-1).cpu().numpy()   # (N, 5)
    scores = (probs * np.array([5, 4, 3, 2, 1])).sum(axis=-1)    # (N,)
    return probs, scores


# ------------------------------------------------------------------ #
# Plot                                                                 #
# ------------------------------------------------------------------ #

def make_plot(samples, pred_probs, pred_scores, out_path):
    n = len(samples)
    x = np.arange(len(LEVELS))
    w = 0.38

    fig = plt.figure(figsize=(4.8 * n, 7.2))
    gs  = gridspec.GridSpec(2, n, height_ratios=[1, 1.5], hspace=0.38, wspace=0.38)

    for i, s in enumerate(samples):
        gt_probs  = np.array(s["gt_probs"])
        gt_score  = float(s["gt_score"])

        # ---- thumbnail ----
        ax_img = fig.add_subplot(gs[0, i])
        ax_img.imshow(s["image"])
        ax_img.axis("off")
        ax_img.set_title(s["title"], fontsize=9, pad=4)

        # ---- grouped bar chart ----
        ax_bar = fig.add_subplot(gs[1, i])
        bars_pred = ax_bar.bar(x - w / 2, pred_probs[i], w,
                               color=PRED_COLOR, label=f"Pred ({pred_scores[i]:.2f})",
                               edgecolor="white", linewidth=0.5)
        bars_gt   = ax_bar.bar(x + w / 2, gt_probs, w,
                               color=GT_COLOR,  label=f"GT ({gt_score:.2f})",
                               edgecolor="white", linewidth=0.5, alpha=0.85)

        ax_bar.set_xticks(x)
        ax_bar.set_xticklabels(LEVELS, fontsize=8)
        ax_bar.set_ylim(0, 1)
        ax_bar.set_ylabel("Probability", fontsize=9)
        ax_bar.tick_params(axis="y", labelsize=8)
        ax_bar.legend(fontsize=7.5, loc="upper right")
        ax_bar.set_title("Predicted vs. Ground Truth", fontsize=9, pad=4)

        for bar in (*bars_pred, *bars_gt):
            h = bar.get_height()
            if h > 0.05:
                ax_bar.text(
                    bar.get_x() + bar.get_width() / 2, h + 0.012,
                    f"{h:.2f}", ha="center", va="bottom", fontsize=6.5,
                )

    fig.suptitle("ViTForIQA — Predicted vs. Real Ground-Truth Label", fontsize=13, y=1.01)
    fig.savefig(out_path, bbox_inches="tight", dpi=150)
    print(f"Saved demo plot to {out_path}")


# ------------------------------------------------------------------ #
# Main                                                                 #
# ------------------------------------------------------------------ #

_DEFAULT_JSON = os.path.join(
    os.path.dirname(__file__),
    "../data/Data-DeQA-Score/KADID10K/metas/train_kadid_8k_new.json",
)
_DEFAULT_ROOT = os.path.join(
    os.path.dirname(__file__),
    "../data/Data-DeQA-Score",
)


def main(args):
    device = get_device()
    print(f"Device: {device}")

    processor = CLIPImageProcessor.from_pretrained(args.preprocessor_path)
    model     = load_model(args.model_path, args.head_path, device)

    samples = load_dataset_samples(
        json_path   = args.dataset_json,
        data_root   = args.data_root,
        num_samples = args.num_samples,
        seed        = args.seed,
    )

    pil_images  = [s["image"] for s in samples]
    pred_probs, pred_scores = score_images(model, processor, pil_images, device)

    for s, score, probs in zip(samples, pred_scores, pred_probs):
        dist = "  ".join(f"{l}={p:.2f}" for l, p in zip(LEVELS, probs))
        print(f"{s['title']:<30}  pred={score:.2f}  gt={s['gt_score']:.2f}  [{dist}]")

    make_plot(samples, pred_probs, pred_scores, args.out)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--model-path",        default="checkpoints/DeQA-Score-Mix3")
    parser.add_argument("--head-path",         default="checkpoints/DeQA-Score-Mix3/head.bin")
    parser.add_argument("--preprocessor-path", default="./preprocessor")
    parser.add_argument("--dataset-json",      default=_DEFAULT_JSON)
    parser.add_argument("--data-root",         default=_DEFAULT_ROOT)
    parser.add_argument("--num-samples",       type=int, default=4)
    parser.add_argument("--seed",              type=int, default=0)
    parser.add_argument("--out",               default="demo.png")
    args = parser.parse_args()
    main(args)
