CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "./demo_logs"

# Model Constants
IGNORE_INDEX = -100

VISION_CONFIG_DEFAULTS = {
    "hidden_size": 1024,
    "intermediate_size": 4096,
    "num_hidden_layers": 12,
    "num_attention_heads": 16,
    "image_size": 448,
    "patch_size": 14,
    "layer_norm_eps": 1e-6,
    "attention_dropout": 0.0,
}

CHECKPOINTS_DIRNAME = "checkpoints"
CHECKPOINT_CONFIG_FILENAME = "config.json"
CHECKPOINT_MODEL_FILENAME = "pytorch_model.bin"
CHECKPOINT_HEAD_FILENAME = "head.bin"
CHECKPOINT_METADATA_FILENAME = "metadata.json"
CHECKPOINT_METADATA_VERSION = 1
CHECKPOINT_AUTO_DIR_PREFIX = "vit-iqa"
CHECKPOINT_HASH_PREFIX_LENGTH = 12
DEQA_SCORE_MIX3_CHECKPOINT_PATH = "checkpoints/vit-iqa-5ca5f1ae52f1"
DEQA_SCORE_MIX3_HF_REPO_ID = "zhiyuanyou/DeQA-Score-Mix3"
DEQA_SCORE_MIX3_VIT_SHARD_FILENAME = "model-00004-of-00004.safetensors"

CHECKPOINT_CONFIG_METADATA_FIELDS = (
    "model_type",
    "hidden_size",
    "intermediate_size",
    "num_hidden_layers",
    "num_attention_heads",
    "image_size",
    "patch_size",
    "layer_norm_eps",
    "attention_dropout",
    "num_quality_levels",
    "softkl_loss",
    "weight_rank",
    "weight_softkl",
    "continuous_rating_loss",
    "binary_rating_loss",
    "use_fix_std",
    "detach_pred_std",
)

IQA_HEAD_STATE_KEYS = ("ln.weight", "ln.bias", "head.weight", "head.bias")

TRAIN_LOCAL_ARG_SPECS = (
    {
        "flags": ("--model-path",),
        "kwargs": {
            "default": DEQA_SCORE_MIX3_CHECKPOINT_PATH,
        },
    },
    {
        "flags": ("--data-path",),
        "kwargs": {
            "required": True,
            "help": "JSON file generated by build_soft_labels/gen_soft_label.py",
        },
    },
    {
        "flags": ("--image-folder",),
        "kwargs": {
            "required": True,
            "help": "Base directory prepended to each sample's 'image' field",
        },
    },
    {
        "flags": ("--preprocessor-path",),
        "kwargs": {
            "default": "preprocessor",
            "help": "Path to image preprocessor config (AutoImageProcessor)",
        },
    },
    {
        "flags": ("--steps",),
        "kwargs": {
            "type": int,
            "default": 50,
        },
    },
    {
        "flags": ("--warmup-steps",),
        "kwargs": {
            "type": int,
            "default": 5,
            "help": "LR linearly ramps from 0 to --lr over this many steps (default: 5)",
        },
    },
    {
        "flags": ("--batch-size",),
        "kwargs": {
            "type": int,
            "default": 4,
        },
    },
    {
        "flags": ("--lr",),
        "kwargs": {
            "type": float,
            "default": 1e-3,
        },
    },
    {
        "flags": ("--log-every",),
        "kwargs": {
            "type": int,
            "default": 5,
        },
    },
    {
        "flags": ("--save-head",),
        "kwargs": {
            "default": None,
            "metavar": "PATH",
            "help": "Save trained head weights (default: <model-path>/head.bin)",
        },
    },
    {
        "flags": ("--run-demo",),
        "kwargs": {
            "action": "store_true",
            "help": "Run demo.py with the trained model after training",
        },
    },
    {
        "flags": ("--demo-out",),
        "kwargs": {
            "default": "demo.png",
            "metavar": "PATH",
            "help": "Output path for the demo plot (default: demo.png)",
        },
    },
)

DOWNLOAD_BACKBONE_ARG_SPECS = (
    {
        "flags": ("--output-dir",),
        "kwargs": {
            "default": DEQA_SCORE_MIX3_CHECKPOINT_PATH,
            "help": f"Directory to write {CHECKPOINT_MODEL_FILENAME} into",
        },
    },
)

DEMO_DEFAULT_DATASET_JSON = "../data/Data-DeQA-Score/KADID10K/metas/train_kadid_8k_new.json"
DEMO_DEFAULT_DATA_ROOT = "../data/Data-DeQA-Score"
DEMO_LEVELS = ("excellent", "good", "fair", "poor", "bad")
DEMO_PRED_COLOR = "#3498db"
DEMO_GT_COLOR = "#e67e22"

DEMO_ARG_SPECS = (
    {
        "flags": ("--model-path",),
        "kwargs": {
            "default": DEQA_SCORE_MIX3_CHECKPOINT_PATH,
        },
    },
    {
        "flags": ("--head-path",),
        "kwargs": {
            "default": None,
            "help": "Optional explicit head weights path; default loads head.bin from the resolved checkpoint.",
        },
    },
    {
        "flags": ("--preprocessor-path",),
        "kwargs": {
            "default": "./preprocessor",
        },
    },
    {
        "flags": ("--dataset-json",),
        "kwargs": {
            "default": DEMO_DEFAULT_DATASET_JSON,
        },
    },
    {
        "flags": ("--data-root",),
        "kwargs": {
            "default": DEMO_DEFAULT_DATA_ROOT,
        },
    },
    {
        "flags": ("--num-samples",),
        "kwargs": {
            "type": int,
            "default": 4,
        },
    },
    {
        "flags": ("--seed",),
        "kwargs": {
            "type": int,
            "default": 0,
        },
    },
    {
        "flags": ("--out",),
        "kwargs": {
            "default": "demo.png",
        },
    },
)
